/**
 * Represents a user in the system who can have favorite locations.
 */
export interface User {
  /** Unique identifier for the user */
  id: string
  /** User's chosen username */
  username: string
}

/**
 * Data transfer object for creating a new user.
 * Only requires a username; the ID will be generated by the backend.
 */
export interface UserCreate {
  /** Username for the new user */
  username: string
}
